PD_VC_Pulse1:
	establish_loop
	sound_play MusicData_VisionaryCastle_Pulse1_1
	sound_play MusicData_VisionaryCastle_Pulse1_1
	sound_play MusicData_VisionaryCastle_Pulse1_1
	sound_play MusicData_VisionaryCastle_Pulse1_2
	sound_play MusicData_VisionaryCastle_Pulse1_3
	sound_play MusicData_VisionaryCastle_Pulse1_3
	sound_play MusicData_VisionaryCastle_Pulse1_4
	sound_play MusicData_VisionaryCastle_Pulse1_4
	sound_play MusicData_VisionaryCastle_Pulse1_5
	pat_ret

PD_VC_Pulse2:
	pitch_inc_switch
	establish_loop
	sound_play MusicData_VisionaryCastle_Pulse2_1
	sound_play MusicData_VisionaryCastle_Pulse2_1
	sound_play MusicData_VisionaryCastle_Pulse2_1
	sound_play MusicData_VisionaryCastle_Pulse2_2
	sound_play MusicData_VisionaryCastle_Pulse2_3
	sound_play MusicData_VisionaryCastle_Pulse2_3
	sound_play MusicData_VisionaryCastle_Pulse2_3
	sound_play MusicData_VisionaryCastle_Pulse2_3
	sound_play MusicData_VisionaryCastle_Pulse2_4
	pat_ret

PD_VC_Hill
	establish_loop
	sound_play MusicData_VisionaryCastle_Hill_1
	sound_play MusicData_VisionaryCastle_Hill_2
	sound_play MusicData_VisionaryCastle_Hill_2
	sound_play MusicData_VisionaryCastle_Hill_2
	sound_play MusicData_VisionaryCastle_Hill_3
	sound_play MusicData_VisionaryCastle_Hill_3
	sound_play MusicData_VisionaryCastle_Hill_4
	pat_ret

PD_VC_Noise:
	establish_loop
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_2
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_3
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_4
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_1
	sound_play MusicData_VisionaryCastle_Noise_5
	pat_ret

PD_VC_FDS:
	establish_loop
	sound_play MusicData_VisionaryCastle_FDS_1
	sound_play MusicData_VisionaryCastle_FDS_2
	sound_play MusicData_VisionaryCastle_FDS_2
	sound_play MusicData_VisionaryCastle_FDS_2
	sound_play MusicData_VisionaryCastle_FDS_3
	sound_play MusicData_VisionaryCastle_FDS_4
	sound_play MusicData_VisionaryCastle_FDS_4
	sound_play MusicData_VisionaryCastle_FDS_4
	sound_play MusicData_VisionaryCastle_FDS_5
	sound_play MusicData_VisionaryCastle_FDS_4
	sound_play MusicData_VisionaryCastle_FDS_4
	sound_play MusicData_VisionaryCastle_FDS_4
	sound_play MusicData_VisionaryCastle_FDS_4
	sound_play MusicData_VisionaryCastle_FDS_4
	sound_play MusicData_VisionaryCastle_FDS_4
	sound_play MusicData_VisionaryCastle_FDS_5
	sound_play MusicData_VisionaryCastle_FDS_6
	sound_play MusicData_VisionaryCastle_FDS_7
	sound_play MusicData_VisionaryCastle_FDS_7
	sound_play MusicData_VisionaryCastle_FDS_8
	pat_ret
